name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      name: ${{ vars.PERSON_NAME }}
      talent: ${{ secrets.TALLENT }}
